apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-ks-plugins
  description: Kitchen-sink service that exercises RHDH plugin tabs
  tags:
    - nodejs
    - udi
    - demo
    - plugins
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rmallam/demo-ks-plugins
    jenkins.io/job-full-name: demo/demo-ks-plugins
    sonarqube.org/project-key: demo-ks-plugins
    argocd/app-name: developer-hub
    argocd/app-namespace: openshift-gitops
    backstage.io/kubernetes-id: demo-ks-plugins
    backstage.io/kubernetes-namespace: demo-dev
    vault.io/secrets-path: rhdh
    jira/project-key: DEMO
    jira/component: demo-ks-plugins
    snyk.io/org-id: stub-org
    snyk.io/org-name: stub-org
    snyk.io/project-ids: stub
    servicenow.com/entity-id: demo
    jfrog-artifactory/image-name: demo-ks-plugins
    dynatrace.com/dynatrace-entity-id: SERVICE-DEMO
    acme.io/devfile-path: devfile.yaml
    acme.io/devspaces-url: https://devspaces.apps.rosa.rosa-89s85.bhg0.p3.openshiftapps.com
    acme.io/devspaces-factory-url: https://devspaces.apps.rosa.rosa-89s85.bhg0.p3.openshiftapps.com/f?url=https://github.com/rmallam/demo-ks-plugins&new
spec:
  type: service
  lifecycle: experimental
  owner: user:default/guest
  system: plugin-kitchen-sink
